__all__ = ("values", "schema")

values: list = [
    {
        "name": "Tokyo",
        "population": 13929286,
        "country": "Japan",
        "founded": "1457",
        "area": 2191.0,
        "language": "Japanese",
    },
    {
        "name": "London",
        "population": 8982000,
        "country": "United Kingdom",
        "founded": "43 AD",
        "area": 1572.0,
        "language": "English",
    },
    {
        "name": "New York City",
        "population": 8399000,
        "country": "United States",
        "founded": "1624",
        "area": 468.9,
        "language": "English",
    },
    {
        "name": "Mumbai",
        "population": 18500000,
        "country": "India",
        "founded": "7th century BC",
        "area": 603.4,
        "language": "Hindi, English",
    },
    {
        "name": "Cape Town",
        "population": 433688,
        "country": "South Africa",
        "founded": "1652",
        "area": 400.0,
        "language": "Afrikaans, English",
    },
    {
        "name": "Paris",
        "population": 2148000,
        "country": "France",
        "founded": "3rd century BC",
        "area": 105.4,
        "language": "French",
    },
    {
        "name": "Beijing",
        "population": 21710000,
        "country": "China",
        "founded": "1045",
        "area": 16410.54,
        "language": "Mandarin",
    },
    {
        "name": "Rio de Janeiro",
        "population": 6747815,
        "country": "Brazil",
        "founded": "1 March 1565",
        "area": 1264.0,
        "language": "Portuguese",
    },
    {
        "name": "Moscow",
        "population": 12506468,
        "country": "Russia",
        "founded": "1147",
        "area": 2511.0,
        "language": "Russian",
    },
    {
        "name": "Sydney",
        "population": 5312163,
        "country": "Australia",
        "founded": "1788",
        "area": 12144.6,
        "language": "English",
    },
    {
        "name": "Berlin",
        "population": 3669491,
        "country": "Germany",
        "founded": "1237",
        "area": 891.8,
        "language": "German",
    },
    {
        "name": "Istanbul",
        "population": 15462482,
        "country": "Turkey",
        "founded": "660 BC",
        "area": 5461.0,
        "language": "Turkish",
    },
    {
        "name": "Lagos",
        "population": 14913700,
        "country": "Nigeria",
        "founded": "15th century",
        "area": 1171.3,
        "language": "English",
    },
    {
        "name": "Bangkok",
        "population": 10089267,
        "country": "Thailand",
        "founded": "1782",
        "area": 1568.7,
        "language": "Thai",
    },
    {
        "name": "Toronto",
        "population": 2930000,
        "country": "Canada",
        "founded": "1750",
        "area": 630.2,
        "language": "English, French",
    },
    {
        "name": "Dubai",
        "population": 3013000,
        "country": "United Arab Emirates",
        "founded": "1833",
        "area": 4114.0,
        "language": "Arabic",
    },
    {
        "name": "Mexico City",
        "population": 8918653,
        "country": "Mexico",
        "founded": "1325",
        "area": 1485.0,
        "language": "Spanish",
    },
    {
        "name": "Stockholm",
        "population": 975551,
        "country": "Sweden",
        "founded": "1187",
        "area": 188.0,
        "language": "Swedish",
    },
    {
        "name": "Seoul",
        "population": 9720846,
        "country": "South Korea",
        "founded": "18 BC",
        "area": 605.2,
        "language": "Korean",
    },
    {
        "name": "Rome",
        "population": 2870500,
        "country": "Italy",
        "founded": "753 BC",
        "area": 1285.0,
        "language": "Italian",
    },
]

from orso.schema import RelationSchema, FlatColumn
from orso.types import OrsoTypes
from data_expectations import Expectation, Behaviors

schema = RelationSchema(
    name="cities",
    columns=[
        FlatColumn(name="name", type=OrsoTypes.VARCHAR, nullable=False),
        FlatColumn(
            name="population",
            type=OrsoTypes.INTEGER,
            expectations=[
                Expectation(
                    expectation=Behaviors.EXPECT_COLUMN_VALUES_TO_BE_MORE_THAN,
                    column="population",
                    config={"threshold": 0},
                )
            ],
        ),
        FlatColumn(name="country", type=OrsoTypes.VARCHAR, nullable=False),
        FlatColumn(name="founded", type=OrsoTypes.VARCHAR, nullable=True),
        FlatColumn(name="area", type=OrsoTypes.DOUBLE),
        FlatColumn(name="language", type=OrsoTypes.VARCHAR),
    ],
)
