name: Wheels

#on:
#  workflow_dispatch:
#  pull_request:
#  push:
#    branches:
#     - master
#  release:
#    types:
#      - published
on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@master

    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install Python package dependencies
      run: python -m pip install --upgrade cython wheel numpy build setuptools

    - name: Build wheels on macOS universal2
      shell: bash
      env:
        ARCHFLAGS: "-arch x86_64 -arch arm64"
        MACOSX_DEPLOYMENT_TARGET: "11.0"
      run: python setup.py bdist_wheel --universal2 --plat-name=macosx_11_0_universal2

    - name: Build wheels on macOS universal2 - take 2
      shell: bash
      env:
        ARCHFLAGS: "-arch x86_64 -arch arm64"
        MACOSX_DEPLOYMENT_TARGET: "11.0"
      run: python -m wheel --universal --architectures "x86_64 arm64" .

