name: Secrets Scanner

on:
  push

jobs:
  fides:
    name: Fides Secrets Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: fides-scanner
        uses: joocer/fides@master