name: Static Analysis

on:
  - push

jobs:
  test:
    name: Bandit Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set Up Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade bandit

      - name: Execute Test
        run: bandit -r mabel

  semgrep:
    runs-on: ubuntu-latest
    name: SemGrep
    steps:
      - uses: actions/checkout@v1
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c


  mypy:
    name: Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set Up Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip mypy
          pip install -r $GITHUB_WORKSPACE/tests/requirements.txt

      - name: Execute Test
        run: mypy --ignore-missing-imports --python-version 3.10 --no-strict-optional --check-untyped-defs orso

  perflint:
    name: PyLint and PerfLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set Up Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip pylint perflint
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install -r $GITHUB_WORKSPACE/tests/requirements.txt

      - name: Execute Test
        run: pylint --fail-under=6 --load-plugins perflint orso