---

name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: raspios_lite:2022-04-04
      
    - name: Set up QEMU
      if: matrix.cibw_archs == 'aarch64'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build wheels for CPython 3.11
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_BUILD: "cp311-*"
        CIBW_ARCHS: ${{ matrix.cibw_archs }}

    - name: Build wheels for CPython 3.10
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_BUILD: "cp310-*"
        CIBW_ARCHS: ${{ matrix.cibw_archs }}

    - name: Build wheels for CPython 3.9
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_BUILD: "cp39-*"
        CIBW_ARCHS: ${{ matrix.cibw_archs }}

    - name: Build wheels for CPython 3.8
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_BUILD: "cp38-*"
        CIBW_ARCHS: ${{ matrix.cibw_archs }}

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
